[pytest]
addopts = -s -v --alluredir=allure-results
markers =
    positive: positive test cases
    negative: negative test cases
    integration: integration test cases
    group(name): MakeyIS group marker

pythonpath = .
